### ISSUE TITLE
Seperate asm files for enemy statistics and formations for easier hacking

### ISSUE THREAD

**Issue by Zuccace** [lory90/ps2disasm#5]
If it's ok I can can start working on it.
I already have been testing it on my [challenge-mode brach](https://github.com/Zuccace/ps2disasm/blob/challenge-mode/ps2.enemystats.asm). Hit points there are spread over two lines, so combining them to a single **dc.w** line would be one of the fixes too.
I can also add short comments to each line like:
```
 ; EXP
 ; MES
 ; ATK
 ; DEF
 ...
```

Of course keeping all the stats in "vanilla" PSII form.
Do you have any other suggestions on the formatting?

Also since I'm not very used yet to the AS compiler (and its manual is HUGE)... While browsing the code I've seen values not starting with $. Does this mean the values missing the $ are in decimal, not hex? If so, can values also be presented as binary?

**Comment by lory90** [comment]
The formatting like you described is fine. That would help a lot in editing enemy stats.

You can write numbers in different formats: $10 is a hex number, 16 (no prefix) is a decimal number, and %00010000 is a binary number.

**Comment by Zuccace** [comment]
Ok. Thanks for the info.
I'll start modifying my fork and when it's ready and tested I'll make a PR.

**Comment by Zuccace** [comment]
I've processed the enemy data file with awk. I'm almost done.

This is one sample among others.
```
Enemy_Aerotank:
        dc.w     $0000, $0220, $0442, $0664, $0886, $0AA8, $0CCA, $0EEC, $0EEE, $0EC8, $0EA0, $0E60, $0C20, $0800, $000E
        dc.l    Battle_VanArt
        dc.w     2709   ; EXP
        dc.w     1080   ; MES
        dc.w     168    ; ATTACK
        dc.w     144    ; DEFENCE
        dc.b     $40    ; TYPE
        dc.b     76     ; AGILITY
        dc.w     306    ; HITPOINTS
        dc.b     $E2    ; TECH/ABILITY
        dc.b     102    ; TECH/ABILITY FREQ (0-255)
        dc.b     $0C    ; EnemyTechSuccessRate table index id/number
        dc.b     76     ; Chances to run (0-255)
        dc.b     $0F    ; Init obj prop
        dc.b     3      ; Animation frame delay (0-255)
        dc.b     $64, $1C, $64, $1C     ; Unknown data - Two words?
        dc.b    SFXID_VanAttack, SFXID_ArmyEyeAttack
        dc.l    Battle_VanMap
        dc.b     $5A, $5A       ; Enemy ID twice?
```

However, I noticesd some inconsistency in the data. Some enemy data is written in different way than my awk script expects. Like Elephant.

When the data is presented in bytes instead of words - comes the error.
I need add word/byte checks and make the script abort the process if there's still too many "fields" of data inside a Enemy_*: subroutine.

Oh well... I't slowly coming together. :P

**Comment by Zuccace** [comment]
Any comments on the data layout / format?
```
Enemy_Mushroom:
         dc.w   $0002, $0204, $0406, $0608, $082A, $0A4C, $0C6E, $00EE, $00AE, $006A, $0026, $000E, $0008, $0004, $0000  ; Palette data
        dc.l    Battle_CarrierArt
         dc.w   101      ; EXPERIENCE POINTS
         dc.w   124      ; MESETA
         dc.w   36       ; ATTACK
         dc.w   29       ; DEFENSE
         dc.b   %00100000        ; Enemy type (%00100000 - biomonster, %01000000 - robot, %01100000 - both)
         dc.b   43       ; AGILITY (0-255)
         dc.w   54       ; HITPOINTS
         dc.b   $00      ; Enemy tech (index number from EnemyTechniqueTable)
         dc.b   0        ; Chances of using tech instead of attack (0-255)
         dc.b   $00      ; Tech success rate (index number from EnemyTechSuccessRate table)
         dc.b   76       ; Chances of escaping from (0-255)
         dc.b   %00001111        ; Initial object properties
         dc.b   3        ; Animation frame delay
         dc.b   $6C, $00, $6C, $00       ; Unknown data
        dc.b    SFXID_TerakiteAttack
        dc.b    SFXID_TerakiteAttack
        dc.l    Battle_CarrierMap
         dc.b   $17, $17         ; Enemy id (twice?)```

I need to fix the identation at least. Also labels for sound effects are missing.

But mainly, do the labels (comments) look ok?

**Comment by lory90** [comment]
Yeah, looks good to me. Thanks for all that work!

**Comment by Zuccace** [comment]
PR #6 fixes this issue.
