### ISSUE TITLE
Split the rest human-readable data, and convert to even more human-readable (decimals mainly)

### ISSUE THREAD

**Issue by Zuccace** [lory90/ps2disasm#7]
At least dialogs/scripts can be seperated and also experience tables.
I've dome some work on my [split-all-the-things -branch](https://github.com/Zuccace/ps2disasm/tree/split-all-the-things). And by converting to more human-readable I mean replacing some hex values with decimal, just like in ps2.enemydata.asm.

The problem I have is that some of the data, mainly enemy data, would need more than one file. For example enemy names, stats and formations are in different, not adjacent, places of the assembly code. Thus they cannot be included using one single file... unless I were to change some subroutines, which would then result in different output binary (if diffed against the original).
Do you got any ideas how to avoid several files?

**Comment by lory90** [comment]
Don't worry about it, even if they are in multiple files. I don't think there's we can do if we need to keep it the same size as the original.

Can I make a suggestion? Could you split the data in different folders rather than having them in the same one as the main asm file? I worry that it will get cumbersome soon. For example you could move the enemy data asm in an enemy folder.

**Comment by Zuccace** [comment]
> Could you split the data in different folders rather than having them in the same one as the main asm file?
Yes. I've been thinking about that actually. :) I'll start moving the data and create new directories.

I noticed that "binclude" has offset arguments, which you can specify to include just parts of the binary. Shame that normal "include" doesn't have similar, like "include file startmark endmark". :|
Anyway. I'll do the splits as neatly as possible. Meaning that for example enemy names will be in seperate asm file. :| Seems like a waste, but what can you do...

**Comment by Zuccace** [comment]
Yup. I'll do what is possible with 'include' and directories. ;)

**Comment by Zuccace** [comment]
The progress so far: https://github.com/Zuccace/ps2disasm/tree/split-all-the-things

The human-readable part is still in progress. For that I'll need to modify my awk script I created for the enemy data conversion. And speaking of the enemy data... [see this post](http://pscave.com/forums/viewtopic.php?p=58971#p58971).

**Comment by lory90** [comment]
Nice work!

I saw your post about the enemy data. I never played around with enemy bytes. Did you actually confirm that the last 2 bytes of the enemy data affect the animation? If so, I could add notes. Or you could do that and send a pull request. Either way works for me.

**Comment by Zuccace** [comment]
I player around with the bytes little more back then, and it seems that only the second to last byte affects the position of the graphics. It also seems to set the start and stop frames of those animations. The last byte seemed to do nothing, but I really didn't test it much. Same goes for the four unknown consecutive bytes - I did only a quick test and nothing seemed different.

**Comment by Zuccace** [comment]
I'm trying to figure out what's the best way to format level end experience points in the table...
Level can be presented ad a single byte, but the experience points need three bytes. Afaik there's no way to represent three byte long data using single decimal number. Word is too short and longword is too long. :|

**Comment by lory90** [comment]
Oh yeah, I remember that one. That's kind of inconvenient <_<

How's your PS2 challenge mode hack going?

**Comment by Zuccace** [comment]
I haven't touched the hack at all... for purpose. I'll continue it after I have merged the "data split" I'm working now.

Anyway... To preserve the output binary "bit perfection" I guess I just need to left the Experience point value as is, or preset it as three different bytes and level byte as decimal.
All other data in the table I can easily format.
I'll probably start that on sunday.

**Comment by Zuccace** [comment]
The [current experience table format](https://github.com/Zuccace/ps2disasm/blob/split-all-the-things/data/character/level.asm).
I had values [padded with zeros](https://github.com/Zuccace/ps2disasm/blob/af447021b628ae77b9bf2f11dc3bf746e0be194b/data/character/level.asm) before. I though it's simpler without them.

**Comment by lory90** [comment]
I merged your changes! Thank you for all the work :)

**Comment by Zuccace** [comment]
You're welcome.
I'll start scanning the main assembly for more. :)
I already noticed that not nearly all of the enemy art are split (as bincludes). I'll see what I can do for them...

**Comment by Zuccace** [comment]
I think I'm done for this friday.
I did some preliminary splits https://github.com/Zuccace/ps2disasm/tree/split-all-the-things/data/properties
Do you think they are ok?

**Comment by lory90** [comment]
There's something I noticed just now: labels are also included in the separate asm files (level.asm, formation.asm, etc). This makes searching for them a little harder. For convenience, I would all labels to be in the main asm file, while data is fine where it is. Also data that has pointers in them, I would like them to be in the main asm file.

If you want to keep it the way you did, that's fine! You don't have to change them for me. I will take care of adjusting them on my disasm.

**Comment by Zuccace** [comment]
So for example this:
```
EnemyBattleFormationData:
    include "path\to\formation.asm"
```
... inside **ps2.asm** would be more conveivent? I can make the changes.
I can start working on the changes maybe tomorrow.

**Comment by lory90** [comment]
That's right. This way it's easy to search for the label and then go to the desired asm file without you guessing. I mean, right now it's pretty intuitive where to look, but once you start having tons of separate asm files, it will become a nightmare.

Don't forget to put data with pointers back in the ps2.asm. For example enemies have pointers to the graphics and sprite mappings, like the following

`Enemy_FireAnt:
	dc.w	$068C, $046A, $0248, $0026, $0004, $0002, $0000, $06A6, $0484, $0240, $08AA, $0688, $0466, $0244, $0000	; Palette data
	dc.l	Battle_AntArt	; Pointer to enemy art
	dc.w	3	; EXPERIENCE POINTS
	dc.w	5	; MESETA
	dc.w	3	; ATTACK
	dc.w	4	; DEFENSE
	dc.b	%00100000	; Enemy type (%00100000 - biomonster, %01000000 - robot, %01100000 - both)
	dc.b	23	; AGILITY (0-255)
	dc.w	9	; HITPOINTS
	dc.b	$00	; Enemy tech (index number from EnemyTechniqueTable)
	dc.b	0	; Chances of using tech instead of attack (0-255)
	dc.b	$00	; Tech success rate (index number from EnemyTechSuccessRate table)
	dc.b	178	; Chances of escaping from (0-255)
	dc.b	%00001111	; Initial object properties
	dc.b	3	; Animation frame delay
	dc.b	$6C, $00, $6C, $00	; Unknown data
	dc.b	SFXID_FireAntAttack	; Attack sound id
	dc.b	SFXID_Whip	; Tech sound id
	dc.l	Battle_AntMap	; Sprite mappings
	dc.b	$01, $01	; Enemy id (twice?)`


It has Battle_AntArt and BattleAntMap. So basically all enemy data goes back in the ps2.asm.

Sorry for the trouble :( I still appreciate all the work you're doing!

**Comment by Zuccace** [comment]
Yeah. That change would practically go "backwards" of what I'm doing here.
But I understand that it can help in translating the disassembly into more readable format.
Hacking-wise it can make it harder to edit, since one needs to work with a file of few megabytes in size. And this was my main itention - to make the source more easy to hack by others.

Anyway My intention wasn't to split _all_ the data, but only the parts that you have already modified for easier reading. If I was to continue this the amount of asm files wouldn't be much higher, since most of the files that are relevant to hacking the source are already split... One that's not been splitted yet is the shop data.

If you want I can move enemy data back to the main asm. I'll then _try_ to create an awk script that can do the splitting of certain data if user of the assembly wants so.

**Comment by lory90** [comment]
Yes, please, move the data back to the main.asm. If there's some more stuff I want back, I will take care of it myself.

**Comment by Zuccace** [comment]
I'm working on it on my master branch.
Closing this issue.

**Comment by Zuccace** [comment]
I'm currently developing an awk script that can split and merge the main assembly. This is meant for hackers/modders. The script will only work on this ps2 disassembly.
It should also work on windows if the user has the linux/ubuntu environment installed/activated in windows.
This way we can offer hackers easier access to the data. This may also greatly help those who develop ramdomizers.

**Comment by Zuccace** [comment]
I have made the awk script that splits the data at cartain points.
https://github.com/Zuccace/ps2disasm/blob/helpers/helpers/split.awk
It also writes all the pointer names (as comments) into the main assembly for easier tracking.
I need to create a merger script also.

**Comment by lory90** [comment]
That's neat!

**Comment by Zuccace** [comment]
Thanks.
I've actually made the script to read a special config file which makes it possible to use it with practically any AS Macroassembler disassembly. This means that it'll be compatible with other PS disassemblies too.

I think I'll merge it as an extra tool into my main build script project.
The main reason to use the script is to split the data for hacking and then, if wanted, merge all the split data back.
I will use the scripts for my own PSII hack. And when you make modifications into the main asm I can first merge my split asm files into the main asm and then merge your changes into my project.
